# #############################################################################
# window
# #############################################################################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# 要获取窗口的类、标题或其他信息，请使用 hyprctl clients 命令

# 窗口规则 v1
# windowrule = RULE,WINDOW
# RULE : 一个规则(float, move等)
# WINDOW : 是一个正则表达式
# 纯正则表达式 : 用于匹配窗口类
# title : 后面跟着一个正则表达式用于匹配窗口的标题

# windowrule = float,^(Alacritty)$
# windowrule = move 0 0,title:^(Firefox)$

# 窗口规则 v2
# 与窗口规则 v1保持兼容，但是更灵活
# RULE 字段未变，WINDOW 字段可以放置多个值
# windowrulev2 = float,class:^(Alacritty)$,title:^(Alacritty)$

windowrule = float, file_progress
windowrule = float, file-roller
windowrule = float, confirm
windowrule = float, confirmreset
windowrule = float, dialog
windowrule = float, download
windowrule = float, notification
windowrule = float, error
windowrule = float, splash
windowrule = float, title:branchdialog

windowrulev2 = size 960 760, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$

# blueman-manager
windowrulev2 = opacity 0.85 0.75, class:^(blueman-manager)$
windowrulev2 = size 720 560, class:^(blueman-manager)$
windowrulev2 = float,class:^(blueman-manager)$

# kitty
windowrulev2 = opacity 0.85 0.75, class:^(kitty)$
windowrulev2 = float, class:^(kitty)$

# nm-applet
windowrulev2 = opacity 0.85 0.75, class:^(nm-applet)$
windowrulev2 = float,class:^(nm-applet)$

# nm-connection-editor
windowrulev2 = opacity 0.85 0.75, class:^(nm-connection-editor)$
windowrulev2 = float,class:^(nm-connection-editor)$

# nmg-look
windowrulev2 = opacity 0.85 0.75, class:^(nwg-look)$
windowrulev2 = size 960 760, class:^(nwg-look)$
windowrulev2 = float, class:^(nwg-look)$

# ncmpcpp
# windowrulev2 = opacity 0.85 0.75, title:^(ncmpcpp)$
# windowrulev2 = float, title:^(ncmpcpp)$

# mpv
windowrulev2 = opacity 0.85 0.75, class:^(mpv)$
windowrulev2 = size 720 560, class:^(mpv)$
windowrulev2 = float, class:^(mpv)$

# pavucontrol
windowrulev2 = opacity 0.85 0.75, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 720 560, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$

# pcmanfm

# polkit-gnome
windowrulev2 = opacity 0.85 0.75, class:^(polkit-gnome-authentication-agent-1)$
windowrulev2 = float, class:^(polkit-gnome-authentication-agent-1)$

# QT5CT & QT6CT
windowrulev2 = opacity 0.85 0.75, class:^(qt5ct)$
windowrulev2 = float, class:^(qt5ct)$

windowrulev2 = opacity 0.85 0.75, class:^(qt6ct)$
windowrulev2 = float, class:^(qt6ct)$

# raspberrypi
windowrulev2 = opacity 0.85 0.75, class:^(org.raspberrypi.rpi-imager)$
windowrulev2 = size 960 760, class:^(org.raspberrypi.rpi-imager)$
windowrulev2 = float, class: ^(org.raspberrypi.rpi-imager)$

# ventoy
windowrulev2 = opacity 0.85 0.75, class:^(Ventoy2Disk.gtk3)$
windowrulev2 = float, class:^(Ventoy2Disk.gtk3)$

# Zenity
windowrulev2 = opacity 0.85 0.75, class:^(zenity)$
windowrulev2 = float, class:^(zenity)$

# #############################################################################
# workspace
# #############################################################################

windowrulev2 = workspace 2, class:^(.*libreoffice.*)$
windowrulev2 = workspace 2, class:^(@joplin/app-desktop)$
windowrulev2 = workspace 3, class:^(code)$
windowrulev2 = workspace 3, class:^(red-view)$
windowrulev2 = workspace 4, class:^(google-chrome)$
windowrulev2 = workspace 5, title:^(ncmpcpp)$
windowrulev2 = workspace 5, class:^(mpv)$
windowrulev2 = workspace 6, class:^(clash-verge)$
windowrulev2 = workspace 6, class:^(org.raspberrypi.rpi-imager)$
windowrulev2 = workspace 6, class:^(Ventoy2Disk.gtk3)$

# #############################################################################
# layer
# #############################################################################

