# #############################################################################
# window
# #############################################################################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# 要获取窗口的类、标题或其他信息，请使用 hyprctl clients 命令

# blueman-manager
windowrule {
  name = blueman-manager
  match:class = ^(blueman-manager)$
  float = on
  size = 720 560
  center = on
}

#clash-verge
windowrule {
  name = clash-verge
  match:class = ^(clash-verge)$
  workspace = 7
}

#chrome
windowrule {
  name = chrome
  match:class = ^(google-chrome)$
  workspace = 4
}

# code
windowrule {
  name = code
  match:class = ^(code)$
  workspace = 3
}

# joplin
windowrule {
  name = joplin
  match:class = ^(@joplin/app-desktop)$
  workspace = 2
}

# kitty
windowrule {
  name = kitty
  match:class = ^(kitty)$
  float = on
  size = 1440 888
  center = on
}

# libreoffice
windowrule {
  name = libreoffice
  match:class = ^(.*libreoffice.*)$
  workspace = 2
}

# mpv
windowrule {
  name = mpv
  match:class = ^(mpv)$
  float = on
  size = 720 560
  center = on
  workspace = 5
}

# ncmpcpp
windowrule {
  name = ncmpcpp
  match:title = ^(ncmpcpp)$
  float = on
  center = on
  workspace = 5
}

# nm-applet
windowrule {
  name = nm-applet
  match:class = ^(nm-applet)$
  float = on
  center = on
}

# nm-connection-editor
windowrule {
  name = nm-connection-editor
  match:class = ^(nm-connection-editor)$
  float = on
  center = on
}

# nmg-look
windowrule {
  name = nmg-look
  match:class = ^(nwg-look)$
  size = 960 760
  float = on
  center = on
}

# pavucontrol
windowrule {
  name = pavucontrol
  match:class = ^(org.pulseaudio.pavucontrol)$
  float = on
  size = 720 560
  center = on
}

# pcmanfm

# polkit
windowrule {
  name = polkit
  match:class = ^(polkit-gnome-authentication-agent-1)$
  float = on
  center = on
}

# QT5CT & QT6CT
windowrule {
  name = qt5ct
  match:class = ^(qt5ct)$
  float = on
  center = on
}

windowrule {
  name = qt6ct
  match:class = ^(qt6ct)$
  float = on
  center = on
}

# red
windowrule {
  name = red
  match:class = ^(red-view)$
  workspace = 3
}

# rpi-imager
windowrule {
  name = rpi-imager
  match:class = ^(org.raspberrypi.rpi-imager)$
  float = on
  size = 960 760
  center = on
  workspace = 7
}

# steam
windowrule {
    name = steam
    match:class = ^(steam)$
    center = on
    workspace = 6
}

# ventoy
windowrule {
  name = ventoy
  match:class = ^(Ventoy2Disk.gtk3)$
  float = on
  center = on
  workspace = 7
}

# zenity
windowrule {
  name = zenity
  match:class = ^(zenity)$
  float = on
  center = on
}
